# Module to contain the constants and class method Hash will extend
module HashOf
  OF_ARRAY_LAMBDA: ^(Hash, untyped) -> Array[untyped]
  OF_HASH_LAMBDA: ^(Hash, untyped) -> Hash[untyped, untyped]
  OF_HASH_RECURSIVE_LAMBDA: ^(Hash, untyped) -> Hash[untyped, untyped]
  VALID_TYPES: Array[Symbol]
  VERSION: String

  def of: (Symbol type, ?recursive: bool) -> Hash[untyped, untyped]
end
